"""empty message

Revision ID: 643e493387be
Revises: 
Create Date: 2025-07-11 08:14:24.682557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643e493387be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('assunto', sa.String(length=100), nullable=True),
    sa.Column('mensagem', sa.String(length=100), nullable=True),
    sa.Column('respondido', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contato')
    # ### end Alembic commands ###
